services:
  redis:
    container_name: redis-session-store
    image: redis
    command: redis-server --save
    ports:
      - 6379:6379
    networks:
      - net
  server:
    container_name: estagios-server
    build: ./back-end
    ports:
      - '8000:8000'
    networks:
      - net
    depends_on:
      - redis
    environment:
      FRONTEND_URL: '*'
      NODE_ENV: production
      REDIS_URL: redis://redis:6379
  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
    ports:
      - 8081:8081
    networks:
      - net

networks:
  net:
    driver: bridge
