# @name login
# @prompt nameOrEmail
# @prompt password
POST {{baseUrl}}/supervisor/login
Content-Type: application/json
Access-Control-Allow-Credentials: true

{
    "nameOrEmail": "{{nameOrEmail}}",
    "password": "{{password}}"
}

###
# @name register
# @prompt name
# @prompt email
# @prompt password
POST {{baseUrl}}/supervisor/register
Content-Type: application/json
Access-Control-Allow-Credentials: true

{
    "name": "{{name}}",
    "email": "{{email}}",
    "password": "{{password}}",
    "passwordConfirmation": "{{password}}"
}