name: Server CI

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x, 20.x, 22.x]
                # Veja o cronograma de versões suportadas do Node.js em https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v4
              name: Checkout code

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
                  cache-dependency-path: './back-end/package-lock.json'

            - name: Install dependencies
              run: npm ci --if-present --prefix back-end

            - name: Build
              run: npm run build --if-present --prefix back-end

            - name: Run tests
              run: npm run test:ci --prefix back-end
